### ISSUE TITLE
[Bug]: Hitbox issues

### ISSUE THREAD

**Issue by NoahAldahan** [jvondermarck/dinosaur-exploder#12]
The hitboxes of certain game component like the dinosaur and the projectile are too big compared to the image.

**Comment by NoahAldahan** [comment]
The hitboxes of the player and enemy projectile still need to be fixed.

**Comment by jvondermarck** [comment]
The hitbox issue is represented below : 
![image](https://user-images.githubusercontent.com/62793491/167303044-934fc1a9-2556-4c9e-a591-c195e7a54d31.png)
![image](https://user-images.githubusercontent.com/62793491/169356488-b8e10073-0b0d-4614-be10-0da72c240d85.png)

**Comment by nadia12-p** [comment]
Hi, is anyone working on this issue? If not, I'd like to take it.

**Comment by jvondermarck** [comment]
Hi @nadia12-p , you can work on this issue :) I assign it to you.

**Comment by nadia12-p** [comment]
Thank you, I'll be working on it :)

**Comment by nadia12-p** [comment]
Hey I was checking out the project, and I have a couple of questions. Whenever the projectile and dinosaurs touch the edge of the spaceship, the lives should decrease right? Also, do you have any suggestion or idea about how to debug so I can see the hitbox?

**Comment by jvondermarck** [comment]
Hi @nadia12-p ,about your first question yeah definitely if the projectile and the dinosaurs touch the edge of the spaceship, the lives should decrease!

Then, for your second question, if you played the game and tried to get hit when a dinosaur send a projectile, when you want to avoid it,  you'll see that your life will decrease because the the picture is too big (hitbox issue) , so my advice is to edit the projectile image ans crop it.

Look just the message above, I attached two screenshots, you'll understand.

**Comment by nadia12-p** [comment]
Hey @jvondermarck, I cropped the image as you suggested but I think we could open another issue so the hitbox of the spaceship would be more adequate to its shape. Instead of just one box, we could do three boxes that represent the entire spaceship. This way the player could have more freedom escaping the enemyProjectiles and the green dinos. What do you think?

<img width="233" alt="Screen Shot 2022-05-20 at 17 17 07" src="https://user-images.githubusercontent.com/70818848/169619343-774f2f56-ed6c-4777-8b31-a6c5fac2383d.png">

**Comment by jvondermarck** [comment]
Hi @nadia12-p , thanks for working on this issue, I'll review your PR tomorrow ASAP!
That's an excellent idea, you can definitely open a new issue / or use this existing issue to propose this idea! Thank you so much for your interest on the project! 🙂

**Comment by jvondermarck** [comment]
I reopen the issue if @nadia12-p want to work on the spaceship hitbox :)

**Comment by nadia12-p** [comment]
@jvondermarck I think I'm going to work on the red background feature first, if anyone else wants to work on it, feel free! :)

**Comment by jvondermarck** [comment]
@nadia12-p Okay awesome!
Just be careful to not delete any files in the ".idea" folder + the "dinosaur-exploder.iml" file.
Thank you! 🙂

**Comment by nescude** [comment]
Hello, I'd like to work on this issue, my approach to this is using two overlapping hitboxes, one for the spaceship body and one for the wings.

**Comment by jvondermarck** [comment]
Hi @nescude it sounds good to me, I assign this issue to you 👌
